### PR TITLE
add baseurl

### PR DESCRIPTION
**Pull request by infominer33**

### CODE REVIEW

**Comment by miklb** [comment]
The next version will use a `_data` YAML file for navigation.

**Comment by infominer33** [comment]
very cool! but you havent given any hints as to when that may be?

I'm still hoping \ hunting around for some turnkey solution... but I may end up figuring out the web-mentions myself, by hand :)

tbh, i'd rather test out a variety of implementations of what you're cookin' up

**Comment by miklb** [comment]
The framework is in place. It will be a Jekyll theme so you don't have to clone or fork the repository.

If you want to keep an eye on https://github.com/miklb/michaelbishop I will be using this project to work out the kinks as I move to a v2 release. Theme related changes will occur in this repo.

**Comment by infominer33** [comment]
Very cool! Thx for the update.  

In my case, i prefer to copy the repo and keep everything local, this way i can ensure portability.

I’m excited, and will continue to collect resources/learn fundamentals.

You’ll be happy to see my progress, I think.

**Comment by infominer33** [comment]
looks like I am safe to close this.

**Pull request closed without merging**
