### PR TITLE
remove article element which is for some reason preventing sites from dis…

### PR DESCRIPTION
**Pull request by herestomwiththeweather**
…tinguishing likes and rsvps from a plain mention

### CODE REVIEW

**Comment by miklb** [comment]
not sure removing h-entry is the ideal way to accomplish this. I'm actually in process of firing up a new Jekyll project and will be revisiting this project (hopefully over the weekend) and will look closer.

**Comment by herestomwiththeweather** [comment]
cool. thanks. my microformats-fu is weak so i don't know what is going on other than sites that are targets of my rsvps and likes do not accept them but if i remove those lines, then they process them correctly.

**Comment by miklb** [comment]
Mine has definitely gotten better since I last worked on this. Definitely want to fix it.

**Comment by herestomwiththeweather** [comment]
one way i have been trying likes is using the woodwind.xyz reader which brought to my attention that _layouts/post.html references a missing post-like.html file:

https://github.com/miklb/jekyll-indieweb/blob/master/_includes/post.html#L26

**Comment by herestomwiththeweather** [comment]
i can confirm that my suggestion for removing that article element is not a good idea as it breaks sending normal webmentions.

**Pull request closed without merging**
